; test helper
PgUp::{
    ch:=ClickHelper()
    ch.sc("test", [1637,683],,,[655,209],[2680,1129])
    ch.cs("test")
}
`::Reload

ArrJoin( arr )
{
  s := ""
  for i,v in arr
    s .= ", " . v
  return substr(s, 3)
}

ArrMap(f, arrs*){
    minlen := PosInf
    for arr in arrs {
        minlen := Min(minlen, arr.Length)
    }
    if minlen=PosInf or minlen=0 {
        return []
    }
    r := []
    Loop minlen {
        i := A_index
        p := []
        for arr in arrs {
            p.Push(arr[i])
        }
        
        r.Push(f(p*))
    }
    return r
}

SampleData(){
    a := Array()
    i := 200
    while i>0 {
        i:=i-1
        ;a.push(SampleNormalDistributionBounded(5,5/3,5,,,False))
        _NotInUse_SampleBaseNormalDistributionSumForm()
    } 
    ;A_Clipboard := ArrJoin(a)
}

TimeIt(){
    StartTime := A_TickCount
    SampleData
    ElapsedTime := A_TickCount - StartTime
    msgbox "The code took " ElapsedTime
}


; real lib

Pi := ACos(-1)
NegInf := -2e308
PosInf := 2e308

_NotInUse_SampleBaseNormalDistributionPolarForm(mean := 0, stddev := 1) {
    ; slower, kept for reference
    ; generated by deepseek
    static hasBoxMuller := false, spare
    if (hasBoxMuller) {
        hasBoxMuller := false
        return spare * stddev + mean
    }
    u := 0, v := 0, s := 0
    while (s >= 1 || s == 0) {
        u := Random(-1.0, 1.0)
        v := Random(-1.0, 1.0)
        s := u*u + v*v
    }
    mul := Sqrt(-2 * Ln(s) / s)
    spare := v * mul
    hasBoxMuller := true
    return (u * mul) * stddev + mean
}


_NotInUse_SampleBaseNormalDistributionSumForm(mean := 0, stddev := 1) {
    s := 0
    Loop 6 {
        s += Random()
    }
    return (s-3)*Sqrt(2)
}

SampleBaseNormalDistribution(){
    ; box-muller transformation, 0-1 -> (m=0,std=1)
    u1 := Random()
    u2 := Random()
    z1 := Sqrt(-2*Ln(u1))*Cos(2*Pi*u2)
    ;spare := Sqrt(-2*Ln(u1))*Sin(2*Pi*u2)
    ;hasSpare := 1
    return z1
}

SampleNormalDistributionBounded(mean:=0, stddev:=1, maxdev?, lower?, upper?, randomWhenBounded:=True){
    lowerBound := IsSet(lower) ? lower : NegInf
    upperBound := IsSet(upper) ? upper : PosInf
    
    if IsSet(maxdev) {
        lowerBound := Max(lowerBound, mean - maxdev)
        upperBound := Min(upperBound, mean + maxdev)
    }

    base := SampleBaseNormalDistribution()
    r := mean + base * stddev
    if r >= lowerBound and r <= upperBound {
        return r
    }

    if !randomWhenBounded {
        return r<lowerBound?lowerBound:upperBound
    }

    lowerBound := 1.0*(lowerBound=NegInf?mean-1*stddev:lowerBound)
    upperBound := 1.0*(upperBound=PosInf?mean+1*stddev:upperBound)
    return Random(lowerBound,upperBound)
}

Sample2DNormalDistributionBounded(mean:=[0,0], stddev:=[1,1], maxdev?, lower?, upper?, randomWhenBounded:=True){
    x := SampleNormalDistributionBounded(mean[1], stddev[1], IsSet(maxdev)?maxdev[1]:unset, IsSet(lower)?lower[1]:unset, IsSet(upper)?upper[1]:unset, randomWhenBounded)
    y := SampleNormalDistributionBounded(mean[2], stddev[2], IsSet(maxdev)?maxdev[2]:unset, IsSet(lower)?lower[2]:unset, IsSet(upper)?upper[2]:unset, randomWhenBounded)
    return [x,y]
}

class ClickHelper {
    scaleX := 1
    scaleY := 1
    spaceSpreadDivider := 3   ; larger -> more center
    timeSpreadDivider := 3
    savedClicks := Map()

    __New(windowWidth:=1, windowHeight?, setupWidth:=1, setupHeight?) {
        this.scaleX := windowWidth/setupWidth
        this.scaleY := IsSet(setupHeight) && IsSet(windowHeight) ? windowHeight/setupHeight : this.scaleX
    }
    SetSpread(spaceSpreadDivider?, timeSpreadDivider?) {
        if IsSet(spaceSpreadDivider) {
            this.spaceSpreadDivider := spaceSpreadDivider
        }
        if IsSet(timeSpreadDivider) {
            this.timeSpreadDivider := timeSpreadDivider
        }
    }
    SaveClick(label, p, btn:="Left", simpleOffset:=0, minp?, maxp?, t:=0, simpleTimeOffset:=0, mint?, maxt?){
        minp := minp?? [p[1]-simpleOffset, p[2]-simpleOffset]
        maxp := maxp?? [p[1]+simpleOffset, p[2]+simpleOffset]
        mint := mint?? t-simpleTimeOffset
        maxt := maxt?? t+simpleTimeOffset
        this.savedClicks[label]:=[p,btn,minp,maxp,t,mint,maxt]
    }
    _GetSaved(){
        return this.savedClicks
    }
    ClickSaved(label){
        p := this.savedClicks[label]
        this.ClickRandomSleepRandom(p[1],p[2],,p[3],p[4],p[5],,p[6],p[7])
    }
    ClickRandom(p, btn:="Left", simpleOffset:=0, minp?, maxp?){
        minp := minp?? [p[1]-simpleOffset, p[2]-simpleOffset]
        maxp := maxp?? [p[1]+simpleOffset, p[2]+simpleOffset]
        stddevP := ArrMap((x,minx,maxx)=>Min(x-minx, maxx-x) / this.spaceSpreadDivider, p, minp, maxp)
        finalP := Sample2DNormalDistributionBounded(p, stddevP,, minp, maxp)
        Click finalP[1]*this.scaleX, finalP[2]*this.scaleY, btn
    }
    SleepRamdom(t, simpleOffset:=0, mint?, maxt?) {
        mint := mint?? t-simpleOffset
        maxt := maxt?? t+simpleOffset
        stddevT := Min(t-mint, maxt-t) / this.timeSpreadDivider
        finalT := SampleNormalDistributionBounded(t, stddevT,, mint, maxt)
        Sleep finalT
    }
    ClickRandomSleepRandom(p, btn:="Left", simpleOffset:=0, minp?, maxp?, t:=0, simpleTimeOffset:=0, mint?, maxt?){
        this.ClickRandom(p,btn,simpleOffset,minp?,maxp?)
        if t>0 {
            this.SleepRamdom(t,simpleTimeOffset,mint?,maxt?)
        }
    }
    sc(a*){
        this.SaveClick(a*)
    }
    cs(a*){
        this.ClickSaved(a*)
    }
    cr(a*){
        this.ClickRandom(a*)
    }
    sr(a*){
        this.SleepRamdom(a*)
    }
    crsr(a*){
        this.ClickRandomSleepRandom(a*)
    }
}
