; test helper
PgUp::{
    ch:=ClickHelper()
    ch.SaveClick("test", 120,120)
    ch.ClickSaved("test")
}
`::Reload

ArrJoin( arr )
{
  s := ""
  for i,v in arr
    s .= ", " . v
  return substr(s, 3)
}

SampleData(){
    a := Array()
    i := 200
    while i>0 {
        i:=i-1
        a.push(SampleNormalDistributionBounded(5,5/3,5,,,False))
        ;SampleBaseNormalDistribution()
    } 
    A_Clipboard := ArrJoin(a)
}

TimeIt(){
    StartTime := A_TickCount
    SampleData
    ElapsedTime := A_TickCount - StartTime
    msgbox "The code took " ElapsedTime
}


; real lib

Pi := ACos(-1)
NegInf := -2e308
PosInf := 2e308

_NotInUse_SampleBaseNormalDistributionPolarForm(mean := 0, stddev := 1) {
    ; slower, kept for reference
    ; generated by deepseek
    static hasBoxMuller := false, spare
    if (hasBoxMuller) {
        hasBoxMuller := false
        return spare * stddev + mean
    }
    u := 0, v := 0, s := 0
    while (s >= 1 || s == 0) {
        u := Random(-1.0, 1.0)
        v := Random(-1.0, 1.0)
        s := u*u + v*v
    }
    mul := Sqrt(-2 * Ln(s) / s)
    spare := v * mul
    hasBoxMuller := true
    return (u * mul) * stddev + mean
}

SampleBaseNormalDistribution(){
    ; box-muller transformation, 0-1 -> (m=0,std=1)
    u1 := Random()
    u2 := Random()
    z1 := Sqrt(-2*Ln(u1))*Cos(2*Pi*u2)
    ;spare := Sqrt(-2*Ln(u1))*Sin(2*Pi*u2)
    ;hasSpare := 1
    return z1
}

SampleNormalDistributionBounded(mean:=0, stddev:=1, maxdev?, lower?, upper?, randomWhenBounded:=True){
    lowerBound := IsSet(lower) ? lower : NegInf
    upperBound := IsSet(upper) ? upper : PosInf
    
    if IsSet(maxdev) {
        lowerBound := Max(lowerBound, mean - maxdev)
        upperBound := Min(upperBound, mean + maxdev)
    }

    base := SampleBaseNormalDistribution()
    r := mean + base * stddev
    if r >= lowerBound and r <= upperBound {
        return r
    }

    if !randomWhenBounded {
        return r<lowerBound?lowerBound:upperBound
    }

    lowerBound := 1.0*(lowerBound=NegInf?mean-1*stddev:lowerBound)
    upperBound := 1.0*(upperBound=PosInf?mean+1*stddev:upperBound)
    return Random(lowerBound,upperBound)
}

Sample2DNormalDistributionBounded(mean:=[0,0], stddev:=[1,1], maxdev?, lower?, upper?, randomWhenBounded:=True){
    x := SampleNormalDistributionBounded(mean[1], stddev[1], IsSet(maxdev)?maxdev[1]:unset, IsSet(lower)?lower[1]:unset, IsSet(upper)?upper[1]:unset, randomWhenBounded)
    y := SampleNormalDistributionBounded(mean[2], stddev[2], IsSet(maxdev)?maxdev[2]:unset, IsSet(lower)?lower[2]:unset, IsSet(upper)?upper[2]:unset, randomWhenBounded)
    return [x,y]
}

SleepRamdom(t, simpleOffset:=0, mint?, maxt?) {
    mint := mint?? t-simpleOffset
    maxt := maxt?? t+simpleOffset
    stddevT := Min(t-mint, maxt-t) / 3
    finalT := SampleNormalDistributionBounded(t, stddevT,, mint, maxt)
    Sleep finalT
}

class ClickHelper {
    scaleX := 1
    scaleY := 1
    savedClicks := Map()

    __New(windowWidth:=1, windowHeight?, setupWidth:=1, setupHeight?) {
        this.scaleX := windowWidth/setupWidth
        this.scaleY := IsSet(setupHeight) && IsSet(windowHeight) ? windowHeight/setupHeight : this.scaleX
    }
    SaveClick(label, x, y, btn:="Left", simpleOffset:=0, minx?, miny?, maxx?, maxy?, slp:=0){
        minx := minx?? x-simpleOffset
        miny := miny?? y-simpleOffset
        maxx := maxx?? x+simpleOffset
        maxy := maxy?? y+simpleOffset
        this.savedClicks[label]:=[x,y,btn,minx,miny,maxx,maxy]
    }
    _GetSaved(){
        return this.savedClicks
    }
    ClickSaved(label){
        p := this.savedClicks[label]
        this.ClickRandom(p[1],p[2],p[3],,p[4],p[5],p[6],p[7])
    }
    ClickRandom(x, y, btn:="Left", simpleOffset:=0, minx?, miny?, maxx?, maxy?){
        minx := minx?? x-simpleOffset
        miny := miny?? y-simpleOffset
        maxx := maxx?? x+simpleOffset
        maxy := maxy?? y+simpleOffset
        stddevX := Min(x-minx, maxx-x) / 3
        stddevY := Min(y-miny, maxy-y) / 3
        finalX := SampleNormalDistributionBounded(x, stddevX,, minx, maxx)
        finalY := SampleNormalDistributionBounded(y, stddevY,, miny, maxy)
        Click finalX*this.scaleX, finalY*this.scaleY, btn
    }
    ClickRandomSleepRandom(x, y, btn:="Left", simpleOffset:=0, minx?, miny?, maxx?, maxy?, t:=0, simpleTimeOffset:=0, mint?, maxt?){
        this.ClickRandom(x,y,btn,simpleOffset,minx?,miny?,maxx?,maxy?)
        SleepRamdom(t,simpleTimeOffset,mint?,maxt?)
    }
    sc(p*){
        this.SaveClick(p*)
    }
    cs(p*){
        this.ClickSaved(p*)
    }
    cr(p*){
        this.ClickRandom(p*)
    }
    crsr(p*){
        this.ClickRandomSleepRandom(p*)
    }
}
