; test helper
ArrJoin( arr, bracket:="[]" )
{
  s := ""
  for i,v in arr
    if Type(v)="Array" {
        s .= ", " . ArrJoin(v, bracket)
    } else {
        s .= ", " . v
    } 
  return substr(bracket,1,1) . substr(s, 3) . substr(bracket,2,1)
}

SampleData(){
    a := Array()
    i := 200
    while i>0 {
        i:=i-1
        a.push(SampleNormalDistributionBounded(5,5/3,5,,,True))
        ;_NotInUse_SampleBaseNormalDistributionSumForm()
    } 
    A_Clipboard := ArrJoin(a)
}

SampleData2D(){
    a := Array()
    i := 200
    while i>0 {
        i:=i-1
        a.push(Sample2DNormalDistributionBounded([5,5],[5/3,5/3],[5,5],,,True))
        ;_NotInUse_SampleBaseNormalDistributionSumForm()
    } 
    A_Clipboard := ArrJoin(a, "{}")
}


SampleClick(){
    ch:=ClickHelper()
    ch.sc("test", [218,132],,,[113,118],[473,148])
    ch.SetDryRun(1)
    a := Array()
    i := 200
    Loop i {
        a.push(ch.cs("test")[1])
        ;_NotInUse_SampleBaseNormalDistributionSumForm()
    } 
    A_Clipboard := ArrJoin(a, "{}")
}

TimeIt(){
    StartTime := A_TickCount
    SampleData
    ElapsedTime := A_TickCount - StartTime
    msgbox "The code took " ElapsedTime
}


; real lib

Pi := ACos(-1)
NegInf := -2e308
PosInf := 2e308

ArrMap(f, arrs*){
    ; arr can be either array or simple item
    minlen := PosInf
    for arr in arrs {
        if arr is Array {
            minlen := Min(minlen, arr.Length)
        }
    }
    if minlen=PosInf or minlen=0 {
        return []
    }
    r := []
    Loop minlen {
        i := A_index
        p := []
        for arr in arrs {
            if arr is Array {
                p.Push(arr[i])
            } else {
                p.Push(arr)
            }
        }
        
        r.Push(f(p*))
    }
    return r
}

ArrEq(arr1, arr2) {
    ; returns True(1) when equal
    if arr1.Length != arr2.Length {
        return False
    }
    Loop arr1.Length {
        if arr1[A_index] != arr2[A_index] {
            return False
        }
    }
    return True
}

Sum(arr) {
    s:=0
    for i,x in arr {
        s += x
    }
    return s
}

Mul(arr) {
    s:=1
    for i,x in arr {
        s *= x
    }
    return s
}

ArrAdd(arrs*) {
    return ArrMap((x*)=>Sum(x), arrs*)
}

ArrSub(arr, arrOrNum) {
    return ArrMap((x,y)=>x-y, arr, arrOrNum)
}

ArrNeg(arr) {
    return ArrMap((x)=>-x, arr)
}

ArrMul(arrs*) {
    return ArrMap((x*)=>Mul(x), arrs*)
}

ArrDivBy(arr, arrOrNum) {
    return ArrMap((x,y)=>x/y, arr, arrOrNum)
}


ArrContains(arr, val) {
    for x in arr
        if x == val
            return True
    return False
}

DistanceOf(p1, p2) {
    return Sqrt((p2[1]-p1[1])**2+(p2[2]-p1[2])**2)
}

MiddlePointWeighted(p1, p2, percentile) {
    return ArrAdd(ArrMul(p2, percentile), ArrMul(p1, 1-percentile))
}

_NotInUse_SampleBaseNormalDistributionPolarForm(mean := 0, stddev := 1) {
    ; slower, kept for reference
    ; generated by deepseek
    static hasBoxMuller := false, spare
    if (hasBoxMuller) {
        hasBoxMuller := false
        return spare * stddev + mean
    }
    u := 0, v := 0, s := 0
    while (s >= 1 || s == 0) {
        u := Random(-1.0, 1.0)
        v := Random(-1.0, 1.0)
        s := u*u + v*v
    }
    mul := Sqrt(-2 * Ln(s) / s)
    spare := v * mul
    hasBoxMuller := true
    return (u * mul) * stddev + mean
}


_NotInUse_SampleBaseNormalDistributionSumForm(mean := 0, stddev := 1) {
    s := 0
    Loop 6 {
        s += Random()
    }
    return (s-3)*Sqrt(2)
}

SampleBaseNormalDistribution(){
    ; box-muller transformation, 0-1 -> (m=0,std=1)
    u1 := Random()
    u2 := Random()
    z1 := Sqrt(-2*Ln(u1))*Cos(2*Pi*u2)
    ;spare := Sqrt(-2*Ln(u1))*Sin(2*Pi*u2)
    ;hasSpare := 1
    return z1
}

SampleNormalDistributionBounded(mean:=0, stddev:=1, maxdev?, lower?, upper?, randomWhenBounded:=True){
    lowerBound := IsSet(lower) ? lower : NegInf
    upperBound := IsSet(upper) ? upper : PosInf
    
    if IsSet(maxdev) {
        lowerBound := Max(lowerBound, mean - maxdev)
        upperBound := Min(upperBound, mean + maxdev)
    }

    base := SampleBaseNormalDistribution()
    r := mean + base * stddev
    if r >= lowerBound and r <= upperBound {
        return r
    }

    if !randomWhenBounded {
        return r<lowerBound?lowerBound:upperBound
    }

    lowerBound := 1.0*(lowerBound=NegInf?mean-1*stddev:lowerBound)
    upperBound := 1.0*(upperBound=PosInf?mean+1*stddev:upperBound)
    return Random(lowerBound,upperBound)
}

Sample2DNormalDistributionBounded(mean:=[0,0], stddev:=[1,1], maxdev?, lower?, upper?, randomWhenBounded:=True){
    x := SampleNormalDistributionBounded(mean[1], stddev[1], IsSet(maxdev)?maxdev[1]:unset, IsSet(lower)?lower[1]:unset, IsSet(upper)?upper[1]:unset, randomWhenBounded)
    y := SampleNormalDistributionBounded(mean[2], stddev[2], IsSet(maxdev)?maxdev[2]:unset, IsSet(lower)?lower[2]:unset, IsSet(upper)?upper[2]:unset, randomWhenBounded)
    return [x,y]
}

GenerateBezierPath(startP, endP, numSegments) {
    dist := DistanceOf(startP, endP)
    ctrlP := ArrAdd(MiddlePointWeighted(startP, endP, Random(0.3, 0.7))
        , Sample2DNormalDistributionBounded([0,0], [dist/9, dist/9], [dist/3, dist/3]))

    path := [startP]
    Loop numSegments-1 {
        t := A_Index / numSegments
        x := (1-t)**2 * startP[1] + 2*(1-t)*t * ctrlP[1] + t**2 * endP[1]
        y := (1-t)**2 * startP[2] + 2*(1-t)*t * ctrlP[2] + t**2 * endP[2]
        p := ArrAdd([x,y], 
            Sample2DNormalDistributionBounded([0,0], [dist/numSegments/9, dist/numSegments/9], [dist/numSegments/3, dist/numSegments/3]))
        path.Push(p)
    }
    path.Push(endP)
    return path
}

MovePath(path, duration, easingType?) {
    totalPoints := path.Length
    startTime := A_TickCount
    
    While 1 {
        elapsed := A_TickCount - startTime
        progress := Min(elapsed / duration, 1.0)
        
        ; translate uniform time progress to eased t
        t := ApplyEasing(progress, easingType?)
        
        currentIndex := Floor(t * (totalPoints - 1)) + 1
        nextIndex := Min(currentIndex + 1, totalPoints)
        
        segmentProgress := (t * (totalPoints - 1)) - (currentIndex - 1)
        currentP := MiddlePointWeighted(path[currentIndex], path[nextIndex], segmentProgress)
        
        MouseMove(currentP[1], currentP[2], 0)
        
        if (A_Index < totalPoints - 2) {
            Sleep 10
        }
        
        if (progress >= 1) {
            MouseMove(path[totalPoints][1], path[totalPoints][2], 0)
            break
        }
    }
}

ApplyEasing(t, mode:="InOutCubic") {
    switch mode {
        case "InQuad": return t * t
        case "OutQuad": return t * (2 - t)
        case "InOutQuad": 
            return (t < 0.5) ? 2 * t * t : -1 + (4 - 2 * t) * t
        case "InCubic": return t * t * t
        case "OutCubic": return (--t) * t * t + 1
        case "InOutCubic":
            return (t < 0.5) ? 4 * t * t * t : (t - 1) * (2 * t - 2) * (2 * t - 2) + 1
        default: return t
    }
}

class WaitHelper {
    dryRun := False
    timeSpreadDivider := 3
    
    SleepRamdom(t, simpleOffset:=0, mint?, maxt?, options:=[]) {
        mint := mint?? t-simpleOffset
        maxt := maxt?? t+simpleOffset
        stddevT := Min(t-mint, maxt-t) / this.timeSpreadDivider
        finalT := SampleNormalDistributionBounded(t, stddevT,, mint, maxt)
        if !this.dryRun {
            Sleep finalT
        }
        return finalT
    }
    sr(a*){
        return this.SleepRamdom(a*)
    }
}

class ClickHelper {
    dryRun := False
    wh := WaitHelper()
    ; mouse click config
    scaleX := 1
    scaleY := 1
    spaceSpreadDivider := 3   ; larger -> more center, smaller -> more spread
    clickHoldAvg := 75
    clickHoldOffset := 25
    ; sometimes we need multiple click to have same relative position
    ; used in option fixedOffset
    fixedOffsetP := [0,0]
    fixedOffsetMinP := [0,0]
    fixedOffsetMaxP := [0,0]
    ; mouse move config
    pathNumSegments := 25
    mouseMoveMaxSpeed := 15 ; in px/ms
    easingMode:= "InOutCubic"
    waitAfterMoveAvg:=50
    waitAfterMoveOffset:=20

    __New(windowWidth:=1, windowHeight?, setupWidth:=1, setupHeight?) {
        this.scaleX := windowWidth/setupWidth
        this.scaleY := IsSet(setupHeight) && IsSet(windowHeight) ? windowHeight/setupHeight : this.scaleX
    }
    RandomizeFixedOffset(simpleOffset?, minp?, maxp?) {
        this.fixedOffsetMinP := minp?? (IsSet(simpleOffset)?[-simpleOffset, -simpleOffset]:this.fixedOffsetMinP)
        this.fixedOffsetMaxP := maxp?? (IsSet(simpleOffset)?[simpleOffset, simpleOffset]:this.fixedOffsetMaxP)
        centerP := ArrMap((minx,maxx)=>(maxx+minx) / 2, this.fixedOffsetMinP, this.fixedOffsetMaxP)
        stddevP := ArrMap((minx,maxx)=>(maxx-minx) / 2 / this.spaceSpreadDivider, this.fixedOffsetMinP, this.fixedOffsetMaxP)
        this.fixedOffsetP := Sample2DNormalDistributionBounded(centerP, stddevP,, this.fixedOffsetMinP, this.fixedOffsetMaxP)
        return this.fixedOffsetP
    }
    SimulatedMouseMove(targetP) {
        MouseGetPos(&startX, &startY)
        path := GenerateBezierPath([startX, startY], targetP, this.pathNumSegments)
        dist := DistanceOf([startX, startY], targetP)
        durationBase:= Max(dist/this.mouseMoveMaxSpeed, 50)
        duration := SampleNormalDistributionBounded(durationBase, durationBase*0.1, durationBase*0.25)
        MovePath(path,duration,this.easingMode)
    }
    ClickRandom(p, btn:="LButton", simpleOffset:=0, minp?, maxp?, options:=[]){
        minp := minp?? [p[1]-simpleOffset, p[2]-simpleOffset]
        maxp := maxp?? [p[1]+simpleOffset, p[2]+simpleOffset]
        stddevP := ArrMap((x,minx,maxx)=>Min(x-minx, maxx-x) / this.spaceSpreadDivider, p, minp, maxp)
        finalP := Sample2DNormalDistributionBounded(p, stddevP,, minp, maxp)
        
        if ArrContains(options, "fixedOffset") {
            finalP := ArrAdd(finalP, this.fixedOffsetP)
        }

        if !this.dryRun {
            this.SimulatedMouseMove([finalP[1]*this.scaleX, finalP[2]*this.scaleY])
            this.wh.SleepRamdom(this.waitAfterMoveAvg, this.waitAfterMoveOffset)
            Send "{" . btn . " Down}"
            this.wh.SleepRamdom(this.clickHoldAvg, this.clickHoldOffset)
            Send "{" . btn . " Up}"
        }
        return finalP
    }
    cr(a*){
        return this.ClickRandom(a*)
    }
}

class InputScheduler {
    ch := ClickHelper()
    wh := WaitHelper()
    savedClicks := Map()
    defaultTimeStdDevRatio := 0.25

    __New(windowWidth:=1, windowHeight?, setupWidth:=1, setupHeight?) {
        this.ch := ClickHelper(windowWidth, windowHeight?, setupWidth, setupHeight?)
    }
    SetSpread(spaceSpreadDivider?, timeSpreadDivider?) {
        if IsSet(spaceSpreadDivider) {
            this.ch.spaceSpreadDivider := spaceSpreadDivider
        }
        if IsSet(timeSpreadDivider) {
            this.wh.timeSpreadDivider := timeSpreadDivider
        }
    }
    SetDryRun(dryRun) {
        this.dryRun:=dryRun
    }
    SaveClick(label, p, kwargs?, btn:="LButton", simpleOffset:=0, minp?, maxp?, t:=0, simpleTimeOffset?, mint?, maxt?, options:=[]){
        if IsSet(kwargs) {
            argsList := ["btn", "simpleOffset", "minp", "maxp", "t", "simpleTimeOffset", "mint", "maxt", "options"]
            for i, arg in argsList {
                %arg% := kwargs.HasOwnProp(arg) ? kwargs.%arg% : (%arg%?)
            }
        }
        minp := minp?? [p[1]-simpleOffset, p[2]-simpleOffset]
        maxp := maxp?? [p[1]+simpleOffset, p[2]+simpleOffset]
        simpleTimeOffset := simpleTimeOffset?? t*this.defaultTimeStdDevRatio
        mint := mint?? t-simpleTimeOffset
        maxt := maxt?? t+simpleTimeOffset
        this.savedClicks[label]:=[p,btn,minp,maxp,t,mint,maxt,options]
    }
    _GetSaved(label?){
        return IsSet(label)? this.savedClicks[label]:this.savedClicks
    }
    ClickSaved(label){
        p := this.savedClicks[label]
        return this.ClickRandomSleepRandom(p[1],p[2],,p[3],p[4],p[5],,p[6],p[7],p[8])
    }
    ClickRandomSleepRandom(p, btn:="LButton", simpleOffset:=0, minp?, maxp?, t:=0, simpleTimeOffset:=0, mint?, maxt?, options:=[]){
        retP := this.ch.ClickRandom(p,btn,simpleOffset,minp?,maxp?,options)
        retT := 0
        if t>0 {
            retT := this.wh.SleepRamdom(t,simpleTimeOffset,mint?,maxt?,options)
        }
        return [retP, retT]
    }
    ExecutePlan(plan){
        for i, step in plan {
            if step is Array {
                i := Random(1, step.Length)
                this.ClickSaved(step[i])
            } else {
                this.ClickSaved(step)
            }
        }
    }
    sc(a*){
        return this.SaveClick(a*)
    }
    cs(a*){
        return this.ClickSaved(a*)
    }
    crsr(a*){
        return this.ClickRandomSleepRandom(a*)
    }
}

GetWinSize(winTitle){
    W:=0,H:=0
    if WinExist(winTitle)
    {
        WinGetClientPos ,, &W, &H, winTitle
    }
    return [W,H]
}